<div class="mask-loader" id="maskLoader"><span class="mask-loader-inner"></span></div>

<!-- Scripts -->
<!-- build:js /js/bundle/core.js -->
{{ js('js/libs/modernizr') }}
{{ js('js/libs/hammer') }}
{{ js('js/libs/jquery') }}
{{ js('js/libs/jquery.ba-cond') }}
{{ js('js/libs/jquery.hammer') }}
{{ js('js/libs/lozad') }}
{{ js('js/libs/base64') }}
{{ js('js/libs/jweixin-1.0.0') }}
{{ js('js/mods/util') }}
{{ js('js/mods/common') }}
{{ js('js/mods/console') }}
<!-- endbuild -->
